package controller;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.image.ImageView;

import javafx.scene.control.Hyperlink;

public class MatchesPageController {
	@FXML
	private ImageView match1Img;
	@FXML
	private ImageView match2Img;
	@FXML
	private ImageView match3Img;
	@FXML
	private ImageView match4Img;
	@FXML
	private Hyperlink match1Link;
	@FXML
	private Hyperlink match2Link;
	@FXML
	private Hyperlink match3Link;
	@FXML
	private Hyperlink match4Link;

	// Event Listener on Button.onAction
	@FXML
	public void backBtnClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
