package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.image.ImageView;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Hyperlink;

public class MatchesPageController {
	@FXML
	private ImageView match1Img;
	@FXML
	private ImageView match2Img;
	@FXML
	private ImageView match3Img;
	@FXML
	private ImageView match4Img;
	@FXML
	private Hyperlink match1Link;
	@FXML
	private Hyperlink match2Link;
	@FXML
	private Hyperlink match3Link;
	@FXML
	private Hyperlink match4Link;
	@FXML
	private Button backBtn;

	// Event Listener on Button.onAction
	@FXML
	public void backBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		FXMLLoader loader = new FXMLLoader();
		Parent root = loader.load(getClass().getResource("/view/ProfilePage.fxml").openStream());
		ProfilePageController profilePageController = (ProfilePageController) loader.getController();
		profilePageController.setUser("vouryex");   // wrong logic
		Stage stage = (Stage) backBtn.getScene().getWindow();
		stage.setTitle("Profile");
		Scene scene = new Scene(root);
		scene.getStylesheets().add("/theme/pastel.css");
		stage.setScene(scene);
		stage.show();
	}
}
