package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Hyperlink;

public class ProfilePageController {
	@FXML
	private Label usernameLbl;
	@FXML
	private Label usernameHead;
	@FXML
	private Hyperlink editLink;
	@FXML
	private Label nameLbl;
	@FXML
	private Label ageLbl;
	@FXML
	private Hyperlink matchesLink;

	// Event Listener on Hyperlink[#matchesLink].onAction
	@FXML
	public void matchesLinkClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getResource("/view/MatchesPage.fxml"));
		Stage stage = (Stage) matchesLink.getScene().getWindow();
		stage.setTitle("Matches");
		Scene scene = new Scene(root);
		scene.getStylesheets().add("/theme/pastel.css");
		stage.setScene(scene);
		stage.show();
	}
	
	public void setUser(String user) {
		usernameLbl.setText(user);
		usernameHead.setText(user);
	}
}
